### ISSUE TITLE
tfe and TbTb: Where is the UnitTestToolbox?

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/temporalFittingEngine#34]
@DavidBrainard : I am unable running into a screen full of updates and errors when I issue `tbUse('temporalFittingEngine','reset','full');`. It appears the TbTb is cloning into my toolbox directory the UnitTestToolbox and the RemoteDataToolbox. Looking a the .json TbTb file for tfe, there is no url given for these toolboxes. 

I'd rather have explicit control over my code directory. What are the URLs for these directories? How does TbTb know where to look for them if they aren't explicitly directed?

**Comment by DavidBrainard** [comment]
Those toolboxes are in the json file as "include" so that they use the tbRegistry entry for the toolbox included to resolve the URL.  This seems like good practice because if one of those toolboxes itself has a dependency we inherit it automatically.

What are the errors?  That part is unexpected.

We should talk about our philosophy on this.  temporalFittingEngine now requires those toolboxes to do the validations, so I think we want them included.

**Comment by gkaguirre** [comment]
Got it. This is a chaining of TbTb registries. That's rather nice.

Now that I know where to look, I will separately check out these repos. At least for now, I like to know what is going on; inevitably the complexity will exceed my ability to track.

I'll post about the error in TbTb. The flavor is that tbUse is incorrectly reporting that I lack an internet connection and then dumps a bunch of errors. My impression is that it is impatient in its ping check.
