### ISSUE TITLE
The IAMP model gives poor fits with some specific instances of data, but these fits are fixed when the linearRegression searchParam is added

### ISSUE THREAD

**Issue by harrison-mcadams** [gkaguirrelab/temporalFittingEngine#49]
I've made simulated data that gets run through the IAMP model to determine amplitude of an evoked response. I've noticed that in some specific instances, the modelResponseStruc fit and consequently the amplitude  do not match the corresponding event. It only happens with a few (seemingly random) instances, but when it does occur the model fit is always an overestimate (gives large amplitude) of the true event. However, the fit is performed properly if the linearRegression searchParam is added.

The attached code should provide a standalone example of an error. The script makes simulated data, then runs the IAMP fit on one specific instance that is affected (subject 1, run 4, instance 3). It presents two plots, with each showing both the actual event (blue) and model fit (orange). In the plot titled "Without Linear Regression Flag", notice the model fit has a larger amplitude than the actual event. But in the plot "With Linear Regression Flag"  the actual event and model fit are identical.

[errorDemo.m.zip](https://github.com/gkaguirrelab/temporalFittingEngine/files/579373/errorDemo.m.zip)

**Comment by gkaguirre** [comment]
I can replicate and correct the error.

The cause of the imperfect fit is the degree of granularity used by fmincon in its search. As currently set, the IAMP model has upper and lower bounds of `realmax`, which are the largest numbers that MATLAB can represent. Given that fmincon needs to search within this enormous range, it gets as close as it can within the available number of iterative searches and then stops.

Near-perfect fits are restored by reducing the upper and lower bounds for the IAMP model. More generally, the `defaultParams` sub-class method for each model should be able to accept passed upper and lower bounds and use these instead of the hard-coded default. I'll leave this issue open until I've implemented the fix.

**Comment by gkaguirre** [comment]
All active models now have the ability to pass initial params, as well as upper and lower boundaries. Specification of reasonable boundaries for the IAMP non-linear search should fix this failure.
