### ISSUE TITLE
Purpose of defaultParamsInfo and defaultParams input args

### ISSUE THREAD

**Issue by spitschan** [gkaguirrelab/temporalFittingEngine#72]
My code is broken after commit dc4ce8a5ae3cf03e4d8162f5b807cdeefe33bbd6. 

What is the purpose of `defaultParamsInfo` and `defaultParams`? The latter only appeared in the most recent commit, gets passed into the `defaultParams` method but the parser for that method doesn't know about the `defaultParams` struct.

Worse, because the MATLAB input parser has partial matching on by default (https://uk.mathworks.com/help/matlab/ref/inputparser.html), it will assume that the passed input argument `defaultParams` is the expected input argument `defaultParamsInfo`.

Example:

My high level code does not pass struct `defaultParams` into the `fitResponse` method. The input parser of `fitResponse` assigns struct `defaultParams` to be the empty matrix. Line 53 of `fitResponse` passes that empty matrix into the `defaultParams` _method_. Partial matching of `defaultParams` with the expected key `defaultParamsInfo` now makes `defaultParamsInfo` to be the empty matrix.

There are multiple ways to fix it but perhaps it would be good to know what the purpose of `defaultParamsInfo` and `defaultParams` is?

**Comment by DavidBrainard** [comment]
defaultParamsInfo was there before, I am not sure what it does.

The idea with defaultParams was to be able to change the default parameters structure returned by the defaultParameters method.  This in turn was done so that we could pass an alternate starting point for the fit to the fit method.  It should be all set up so that nothing bad happens if you don't pass anything -- defaultParams should then get set to empty by the input parser and lead to no change in behavior.  Sounds like we missed at least one spot where we should have done something.  I can take a look, but possibly not for a few days.  If this helps you track down the problem, great. Otherwise perhaps make a branch off the current master and then revert to before our changes on the master, and we can sort it out later while you happily use the old code.

**Comment by DavidBrainard** [comment]
If you do the branch and revert thing, please let me and Michael Barnett know by email, so we aren't confused.

**Comment by gkaguirre** [comment]
Let’s revert for the moment.

To date, the one and only purpose of defaultParamsInfo was to supply the field “nInstances”. I have wanted for some time to do away with this.

Let’s take a look and think about how we want to handle these sorts of params. 

--

Geoffrey Karl Aguirre, MD, PhD
https://cfn.upenn.edu/aguirre
Associate Professor of Neurology
University of Pennsylvania

**Comment by spitschan** [comment]
I suspect that this wouldn't be a problem at all, if `defaultParams` wasn't a substring of `defaultParamsInfo` and therefore gets partially matched by the input parser.

**Comment by DavidBrainard** [comment]
Ah, that's it.  I didn't know about partial matching.  Just turn partial matching off in the relevant places and problem solved for now.
We can then think about how to deal with defaultParamsInfo.

DB

**Comment by spitschan** [comment]
Will do on branch and issue a PR.

**Comment by spitschan** [comment]
Partial matching turned off as of 945cee3f96eddfc7803fcf89e011803d6a1a5693
