### ISSUE TITLE
'errorType' key/value pair to fitResponse not used fully

### ISSUE THREAD

**Issue by DavidBrainard** [gkaguirrelab/temporalFittingEngine#74]
Someone added an errorType key/value pair to the fitResponse method but did not comment it.

This parameter is passed to the fitError method of the subclass when computing the final error, but does not appear to be passed during the actual fitting.  This seems like a bug, or at least worth a careful comment.

I commented the key/value pair (along with others that had been added without updates to the header comment), and put a note about the fact that this does not seem to be fully used. Someone who uses this option might take a look.

**Comment by gkaguirre** [comment]
This issue intersects with the larger topic of how we wish to handle parameters within the tfe.

For now, I have modified fitResponse so that `varargin` is passed to the objective function of fmincon. We will want to switch to an alternative approach in which the object will store these properties instead of engaging in parameter passing.

**Comment by DavidBrainard** [comment]
Sounds good.  Just an additional thought.  There will be some key/value pairs that probably should be passed to methods.  For example, for fitResponse we will probably want to preserve the current ability to override the search starting parameters (which are those returned by defaultParams method, with something that varies according to a particular problem.  This I can see being varied after an object is created.  There may be other examples like this.
